name: .NET Core

on: [push, pull_request]

jobs:
  build:
    name: Build Project
    # Just run on ubuntu. It's much faster than Windows, and the result will most likely be the same.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      #TODO: Finish this cache section
      #- name: Check .NET Core Cache
      #  id: netcore-cache
      #  uses: actions/cache@v2.1.3
      #  with:
      #    key: ${{ runner.os }}-netcore

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "5.0.x"

      - name: Setup Discord.Net MyGet Source
        run: dotnet nuget add source https://www.myget.org/F/discord-net/api/v3/index.json

      - name: Check NuGet Cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Building
        run: dotnet build --configuration Release --no-restore
