name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x'      
      
    - name: Setup MyGet Source
      run: dotnet nuget add source https://www.myget.org/F/discord-net/api/v3/index.json
    
    - name: Building
      run: dotnet build --configuration Release
