name: .NET

on: [push, pull_request]

env:
  DOTNET_VER: 7.x.x

jobs:
  build:    
    name: Build Project
    # Just run on ubuntu. It builds faster than Windows, and the result will most likely be the same.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      
      - name: Check .NET Cache
        id: dotnet-cache
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/
          key: ${{ runner.os }}-dotnet-${{ env.DOTNET_VER }}
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      
      - name: Setup .NET Workloads
        run: dotnet workload install macos
      
      - name: Setup Custom NuGet Sources
        run: dotnet nuget add source https://www.myget.org/F/discord-net/api/v3/index.json

      - name: Check NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore --force-evaluate

      - name: Building
        run: dotnet build --configuration Release --no-restore
