name: .NET

on: [push, pull_request]

env:
  DOTNET_VER: 5.0.x

jobs:
  build:    
    name: Build Project
    # Just run on ubuntu. It builds faster than Windows, and the result will most likely be the same.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Check .NET Cache
        id: dotnet-cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.dotnet/
          key: ${{ runner.os }}-dotnet-${{ env.DOTNET_VER }}
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
  
      - name: Setup NuGet
        run: |
          nuget locals all -clear
      
      - name: Setup Custom NuGet Sources
        run: dotnet nuget add source https://www.myget.org/F/discord-net/api/v3/index.json

      - name: Check NuGet Cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore
        run: dotnet restore

      - name: Building
        run: dotnet build --configuration Release --no-restore
