name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - name: Building
      run: dotnet build --configuration Release
